version: '3.7'
services:
    mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    worker:
      depends_on:
        - mongo
      build:
        dockerfile: Dockerfile
        context: .
      logging:
        options:
          max-size: 10m
          max-file: "3"
      environment:
        MONGODB_ADMINUSERNAME: root
        MONGODB_ADMINPASSWORD: example
        MONGODB_URL: mongodb://root:example@mongo:27017/
