name: Airflow application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
        python-version: 3.9
     - name: Install pipenv
       uses: dschep/install-pipenv-action@v1
     - name: Lint with flake8
       run: |
        pipenv install --dev
        pipenv run flake8 .
